/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.encvstin.jdsec;

import android.widget.LinearLayout;
import android.content.Context;
import android.util.AttributeSet;

public class SquarLinearLayout extends LinearLayout {
    
    public SquarLinearLayout(Context context) {
        super(context);
    }
    
    public SquarLinearLayout(Context context, AttributeSet attrs) {
        super(context, attrs);
    }
    
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, widthMeasureSpec);
    }
}
